# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d4cda0ac-d5f4-43b3-86be-cbb26fbdab39";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-ab9c8154-8464-443b-afaf-c999d4a05da3".device = "/dev/disk/by-uuid/ab9c8154-8464-443b-afaf-c999d4a05da3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B8B4-21AF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/Games" =
    {
      device = "/dev/disk/by-uuid/8774a2b7-1b02-41bf-9cc0-d2cf79dc29a3";
      fsType = "ext4";
      options = [ "default" "exec" "x-gvfs-show" ];
    };

  fileSystems."/mnt/hdd" =
    {
      device = "/dev/disk/by-uuid/ee7fa23f-9120-436c-9c2c-fee976d8dfba";
      fsType = "ext4";
      options = [ "default" "x-gvfs-show" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
